using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using Valheim.Testing.Doubles;
using Xunit;

// What the doubles define and which of it the game lacks (issue #305). The index (docs/packages/Valheim.Testing.Doubles.members.txt)
// is this assembly's doubles, one line per public type and member; the game's verdict on each line (GameBytes/game-members.txt)
// comes from tools/doubles-members/capture-game-members.cs reading the pinned game, BepInEx and Jotunn assemblies. A member
// the game lacks must carry [TestOnly], and one the game has must not, so mod code cannot lean on a doubles-only member unseen.
public sealed class MemberIndexTests
{
    private const string IndexPath = "docs/packages/Valheim.Testing.Doubles.members.txt";
    private const string CapturePath = "tests/Valheim.Testing.Doubles.Tests/GameBytes/game-members.txt";

    private static string Root()
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir != null; dir = dir.Parent)
            if (File.Exists(Path.Combine(dir.FullName, "src", "Valheim.Testing.Doubles", "Valheim.Testing.Doubles.csproj"))) return dir.FullName;
        throw new InvalidOperationException("No repository root above " + AppContext.BaseDirectory);
    }

    /// <summary>The index lines, generated from the doubles compiled into this assembly.</summary>
    public static List<string> IndexLines()
    {
        var source = DoublesSource.Load(typeof(MemberIndexTests).Assembly);
        var lines = new List<string>();
        foreach (var type in typeof(MemberIndexTests).Assembly.GetTypes()
                     .Where(t => MemberIndex.IsDoubledNamespace(t.Namespace) && MemberIndex.VisibleType(t) && source.Declares(t))
                     .OrderBy(MemberIndex.TypeName, StringComparer.Ordinal))
        {
            string name = MemberIndex.TypeName(type);
            bool typeTestOnly = TestOnly(type), typeInternal = !MemberIndex.Public(type);
            lines.Add(name + "\ttype\t" + MemberIndex.Describe(type) + "\t" + (typeTestOnly ? "test-only" : typeInternal ? "internal" : "game"));
            lines.AddRange(MemberIndex.Members(type).Where(source.Declares)
                .Select(m => name + "\t" + MemberIndex.Kind(m) + "\t" + MemberIndex.Signature(m) + "\t"
                    + (typeTestOnly || m.IsDefined(typeof(TestOnlyAttribute), false) ? "test-only" : typeInternal || !MemberIndex.Public(m) ? "internal" : "game"))
                .OrderBy(l => l, StringComparer.Ordinal));
        }
        return lines;
    }

    private static bool TestOnly(Type type) => type.IsDefined(typeof(TestOnlyAttribute), false) || (type.IsNested && TestOnly(type.DeclaringType!));

    private static string Header() => string.Join("\n",
        "# Valheim.Testing.Doubles: every type and member a mod's linked sources can reach, one line each: type, kind, signature, and",
        "# game (the game has it), test-only ([TestOnly] in source: the game lacks it; mod code must not call it) or internal (the",
        "# doubles' own plumbing, internal so it compiles into your test assembly; the game does not show it either). Generated by",
        "# tests/Valheim.Testing.Doubles.Tests/MemberIndexTests.cs: when the doubles change, the test rewrites this file and fails",
        "# once; commit the diff, which is the change list and the names a consumer's own partials may now collide with.");

    [Fact] public void TheIndexListsEveryDoubledMember()
    {
        string path = Path.Combine(Root(), IndexPath);
        string expected = Header() + "\n" + string.Join("\n", IndexLines()) + "\n";
        string actual = File.Exists(path) ? File.ReadAllText(path).Replace("\r\n", "\n") : "";
        if (actual == expected) return;
        File.WriteAllText(path, expected);
        Assert.Fail(IndexPath + " was stale and is now rewritten from the doubles; review and commit the diff.");
    }

    private sealed record Verdict(string Status, string Detail);

    private static Dictionary<string, Verdict> Capture(out string header)
    {
        var verdicts = new Dictionary<string, Verdict>(StringComparer.Ordinal);
        var headerLines = new List<string>();
        foreach (string line in File.ReadAllLines(Path.Combine(Root(), CapturePath)))
        {
            if (line.StartsWith("#", StringComparison.Ordinal)) { headerLines.Add(line); continue; }
            if (line.Length == 0) continue;
            string[] fields = line.Split('\t');
            Assert.True(fields.Length is 4 or 5, "A capture line has type, kind, signature, verdict and optionally the game's own signatures: " + line);
            verdicts.Add(fields[0] + "\t" + fields[1] + "\t" + fields[2], new(fields[3], fields.Length == 5 ? fields[4] : ""));
        }
        header = string.Join("\n", headerLines);
        return verdicts;
    }

    /// <summary>Each index line whose [TestOnly] mark disagrees with the game's verdict, or that the capture lacks.</summary>
    private static List<string> Disagreements(IEnumerable<string> indexLines, Dictionary<string, Verdict> verdicts)
    {
        var problems = new List<string>();
        foreach (string line in indexLines)
        {
            string[] f = line.Split('\t');
            bool testOnly = f[3] == "test-only";
            if (f[3] == "internal") continue; // internal is its own mark: the index flags it as the doubles' plumbing, game name or not
            if (!verdicts.TryGetValue(f[0] + "\t" + f[1] + "\t" + f[2], out var verdict))
                problems.Add("not in the game capture (run tools/doubles-members/capture-game-members.cs against the pinned game): " + line);
            else if (testOnly && verdict.Status == "game") problems.Add("the game has it, so it must not be [TestOnly]: " + line);
            else if (!testOnly && verdict.Status == "differs") problems.Add("the game's signature differs (" + verdict.Detail + "); match it or mark it [TestOnly]: " + line);
            else if (!testOnly && verdict.Status != "game") problems.Add("the game has no such member; mark it [TestOnly]: " + line);
        }
        return problems;
    }

    [Fact] public void TestOnlyMarksExactlyWhatTheGameLacks()
    {
        var problems = Disagreements(IndexLines(), Capture(out _));
        Assert.True(problems.Count == 0, problems.Count + " doubled members disagree with the game:\n" + string.Join("\n", problems));
    }

    [Fact] public void TheCaptureCoversExactlyTheIndex()
    {
        var verdicts = Capture(out string header);
        var index = IndexLines().Select(l => { var f = l.Split('\t'); return f[0] + "\t" + f[1] + "\t" + f[2]; }).ToHashSet(StringComparer.Ordinal);
        Assert.Empty(verdicts.Keys.Where(k => !index.Contains(k)).OrderBy(k => k, StringComparer.Ordinal));
        Assert.Contains("# game assembly_valheim.dll sha256 ", header);
        // The game the doubles copy, by its version string and network version (#308): a game update fails until recaptured.
        Assert.Contains("\n# game version " + DoubledGame.Version + "\n", "\n" + header + "\n");
        Assert.Contains("\n# game network version " + DoubledGame.NetworkVersion + "\n", "\n" + header + "\n");
    }

    // The check's negative side: an unmarked member the game lacks, an unmarked drifted signature, a marked member the game
    // has and a member the capture never saw are each reported, so removing a [TestOnly] (or adding a member) cannot pass.
    [Fact] public void EachDisagreementIsReported()
    {
        var verdicts = Capture(out _);
        Assert.Equal("absent", verdicts["ZNet\tfield\tPeers : Dictionary<long, ZNetPeer> { get; }"].Status);
        Assert.Contains("ZNet\tfield\tPeers : Dictionary<long, ZNetPeer> { get; }\ttest-only", IndexLines());
        var problems = Disagreements(new[]
        {
            "ZNet\tfield\tPeers : Dictionary<long, ZNetPeer> { get; }\tgame",
            "UnityEngine.GameObject\tmethod\tAddComponent<T>(Action<T>) : T\tgame",
            "ZNet\tmethod\tstatic GetUID() : long\ttest-only",
            "ZNet\tmethod\tNotAGameMethod() : void\ttest-only",
        }, verdicts);
        Assert.Collection(problems,
            p => Assert.StartsWith("the game has no such member", p),
            p => Assert.StartsWith("the game's signature differs (AddComponent(Type)", p),
            p => Assert.StartsWith("the game has it, so it must not be [TestOnly]", p),
            p => Assert.StartsWith("not in the game capture", p));
    }

    [Fact] public void WritableDoubleOfReadOnlyGameMemberIsAContractError()
    {
        var verdicts = new Dictionary<string, Verdict>(StringComparer.Ordinal)
        {
            ["Example\tfield\tValue : int"] = new("differs", "Value : int { get; }"),
            ["Example\tfield\tValue : int { get; }"] = new("game", ""),
        };
        Assert.Single(Disagreements(new[] { "Example\tfield\tValue : int\tgame" }, verdicts));
        Assert.Empty(Disagreements(new[] { "Example\tfield\tValue : int { get; }\tgame" }, verdicts));
    }

    [Fact] public void FixtureMembersExposeTheGamesReadOnlySurface()
    {
        Assert.EndsWith(MemberIndex.ReadOnly, MemberIndex.Signature(typeof(ZDOID).GetField(nameof(ZDOID.UserID))!));
        Assert.EndsWith(MemberIndex.ReadOnly, MemberIndex.Signature(typeof(UnityEngine.Time).GetProperty(nameof(UnityEngine.Time.time))!));
        Assert.EndsWith(MemberIndex.ReadOnly, MemberIndex.Signature(typeof(ZNet).GetProperty(nameof(ZNet.instance))!));
        Assert.EndsWith(MemberIndex.ReadOnly, MemberIndex.Signature(typeof(UnityEngine.Component).GetProperty(nameof(UnityEngine.Component.gameObject))!));
        Assert.DoesNotContain(MemberIndex.ReadOnly, MemberIndex.Signature(typeof(Heightmap).GetField(nameof(Heightmap.m_width))!));
    }
}

/// <summary>
/// Which types and members this assembly compiled from the doubles' source files, from its portable PDB. A field has no
/// code, so it counts as its type's: a field a test file's partial adds to a doubled type would be listed as the doubles'.
/// Give such a partial properties instead (DoublesTests.cs does).
/// </summary>
internal sealed class DoublesSource
{
    private static readonly Guid TypeDefinitionDocuments = new("932E74BC-DBA9-4478-8D46-0F32A7BAB3D3");
    private readonly HashSet<int> _doublesMethods = new(), _otherMethods = new(), _doublesTypes = new(), _otherTypes = new();

    public static DoublesSource Load(Assembly assembly)
    {
        var result = new DoublesSource();
        using var stream = File.OpenRead(Path.ChangeExtension(assembly.Location, ".pdb"));
        using var provider = MetadataReaderProvider.FromPortablePdbStream(stream);
        var reader = provider.GetMetadataReader();
        bool FromDoubles(DocumentHandle handle) => reader.GetString(reader.GetDocument(handle).Name).Replace('\\', '/').Contains("/Valheim.Testing.Doubles/Doubles/", StringComparison.Ordinal);
        foreach (var handle in reader.MethodDebugInformation)
        {
            var points = reader.GetMethodDebugInformation(handle).GetSequencePoints().ToList();
            if (points.Count == 0) continue;
            (FromDoubles(points[0].Document) ? result._doublesMethods : result._otherMethods).Add(MetadataTokens.GetRowNumber(handle));
        }
        foreach (var handle in reader.CustomDebugInformation)
        {
            var info = reader.GetCustomDebugInformation(handle);
            if (info.Parent.Kind != HandleKind.TypeDefinition || reader.GetGuid(info.Kind) != TypeDefinitionDocuments) continue;
            int typeRow = MetadataTokens.GetRowNumber((TypeDefinitionHandle)info.Parent);
            var blob = reader.GetBlobReader(info.Value);
            while (blob.RemainingBytes > 0)
                (FromDoubles(MetadataTokens.DocumentHandle(blob.ReadCompressedInteger())) ? result._doublesTypes : result._otherTypes).Add(typeRow);
        }
        return result;
    }

    private static int Row(MemberInfo member) => member.MetadataToken & 0xFFFFFF;

    /// <summary>A type is the doubles' when its source is a doubles file: any method compiled from one, or the PDB's file for a type without code.</summary>
    public bool Declares(Type type)
    {
        if (_doublesTypes.Contains(Row(type))) return true;
        if (_otherTypes.Contains(Row(type))) return false;
        var methods = type.GetMembers(MemberIndex.Declared).SelectMany(Methods).Select(Row).ToList();
        if (methods.Any(_doublesMethods.Contains)) return true;
        if (methods.Any(_otherMethods.Contains)) return false;
        return type.IsNested && Declares(type.DeclaringType!);
    }

    /// <summary>A member is the doubles' when its code comes from a doubles file; a field (no code) belongs to its type.</summary>
    public bool Declares(MemberInfo member)
    {
        var methods = Methods(member).Select(Row).ToList();
        if (methods.Any(_doublesMethods.Contains)) return true;
        if (methods.Any(_otherMethods.Contains)) return false;
        return Declares(member.DeclaringType!);
    }

    private static IEnumerable<MethodBase> Methods(MemberInfo member) => member switch
    {
        MethodBase m => new[] { m },
        PropertyInfo p => p.GetAccessors(true),
        EventInfo e => new[] { e.AddMethod, e.RemoveMethod }.Where(m => m != null).Cast<MethodBase>(),
        _ => Array.Empty<MethodBase>(),
    };
}
